// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XR5_0TrainingRepo.Models;

#nullable disable

namespace XR5_0TrainingRepo.Migrations
{
    [DbContext(typeof(XR50RepoContext))]
    [Migration("20241121082904_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("XR5_0TrainingRepo.Models.Asset", b =>
                {
                    b.Property<string>("AssetId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AppName")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("OwncloudFileName")
                        .HasColumnType("longtext");

                    b.Property<string>("OwncloudPath")
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.Property<string>("ResourceManagementAppName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ResourceManagementResourceName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ResourceManagementTrainingName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ResourceName")
                        .HasColumnType("longtext");

                    b.Property<string>("TrainingName")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("AssetId");

                    b.HasIndex("ResourceManagementAppName", "ResourceManagementTrainingName", "ResourceManagementResourceName");

                    b.ToTable("Asset");
                });

            modelBuilder.Entity("XR5_0TrainingRepo.Models.OwncloudShare", b =>
                {
                    b.Property<string>("ShareId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AppName")
                        .HasColumnType("longtext");

                    b.Property<string>("AssetId")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("OwncloudFileName")
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.Property<string>("ResourceName")
                        .HasColumnType("longtext");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrainingName")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("ShareId");

                    b.ToTable("OwncloudShare");
                });

            modelBuilder.Entity("XR5_0TrainingRepo.Models.QueryStore", b =>
                {
                    b.Property<long>("QueryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("QueryId"));

                    b.Property<string>("Query")
                        .HasColumnType("longtext");

                    b.Property<string>("QueryResponse")
                        .HasColumnType("longtext");

                    b.HasKey("QueryId");

                    b.ToTable("Queries");
                });

            modelBuilder.Entity("XR5_0TrainingRepo.Models.ResourceManagement", b =>
                {
                    b.Property<string>("AppName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TrainingName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ResourceName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("OwncloudFileName")
                        .HasColumnType("longtext");

                    b.HasKey("AppName", "TrainingName", "ResourceName");

                    b.ToTable("Resource");
                });

            modelBuilder.Entity("XR5_0TrainingRepo.Models.TrainingModule", b =>
                {
                    b.Property<string>("AppName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TrainingName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UseCase")
                        .HasColumnType("longtext");

                    b.HasKey("AppName", "TrainingName");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("XR5_0TrainingRepo.Models.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("UserEmail")
                        .HasColumnType("longtext");

                    b.Property<bool>("admin")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("UserName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("XR5_0TrainingRepo.Models.XR50App", b =>
                {
                    b.Property<string>("AppName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AdminName")
                        .HasColumnType("longtext");

                    b.Property<string>("AdminUserUserName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("OwncloudDirectory")
                        .HasColumnType("longtext");

                    b.Property<string>("OwncloudGroup")
                        .HasColumnType("longtext");

                    b.HasKey("AppName");

                    b.HasIndex("AdminUserUserName");

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("XR5_0TrainingRepo.Models.Asset", b =>
                {
                    b.HasOne("XR5_0TrainingRepo.Models.ResourceManagement", null)
                        .WithMany("AssetList")
                        .HasForeignKey("ResourceManagementAppName", "ResourceManagementTrainingName", "ResourceManagementResourceName");
                });

            modelBuilder.Entity("XR5_0TrainingRepo.Models.ResourceManagement", b =>
                {
                    b.HasOne("XR5_0TrainingRepo.Models.TrainingModule", null)
                        .WithMany("ResourceList")
                        .HasForeignKey("AppName", "TrainingName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XR5_0TrainingRepo.Models.TrainingModule", b =>
                {
                    b.HasOne("XR5_0TrainingRepo.Models.XR50App", null)
                        .WithMany("TrainingList")
                        .HasForeignKey("AppName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XR5_0TrainingRepo.Models.XR50App", b =>
                {
                    b.HasOne("XR5_0TrainingRepo.Models.User", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserUserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("XR5_0TrainingRepo.Models.ResourceManagement", b =>
                {
                    b.Navigation("AssetList");
                });

            modelBuilder.Entity("XR5_0TrainingRepo.Models.TrainingModule", b =>
                {
                    b.Navigation("ResourceList");
                });

            modelBuilder.Entity("XR5_0TrainingRepo.Models.XR50App", b =>
                {
                    b.Navigation("TrainingList");
                });
#pragma warning restore 612, 618
        }
    }
}
