// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XR5_0TrainingRepo.Models;

#nullable disable

namespace XR5_0TrainingRepo.Migrations
{
    [DbContext(typeof(XR50RepoContext))]
    partial class XR50RepoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("XR5_0TrainingRepo.Models.Asset", b =>
                {
                    b.Property<string>("AssetId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AppName")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("OwncloudFileName")
                        .HasColumnType("longtext");

                    b.Property<string>("OwncloudPath")
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.Property<string>("ResourceManagementResourceId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ResourceName")
                        .HasColumnType("longtext");

                    b.Property<string>("TrainingName")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("AssetId");

                    b.HasIndex("ResourceManagementResourceId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("XR5_0TrainingRepo.Models.OwncloudShare", b =>
                {
                    b.Property<string>("ShareId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AppName")
                        .HasColumnType("longtext");

                    b.Property<string>("AssetId")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("OwncloudFileName")
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.Property<string>("ResourceName")
                        .HasColumnType("longtext");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrainingName")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("ShareId");

                    b.ToTable("OwncloudShares");
                });

            modelBuilder.Entity("XR5_0TrainingRepo.Models.ResourceManagement", b =>
                {
                    b.Property<string>("ResourceId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AppName")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("OwncloudFileName")
                        .HasColumnType("longtext");

                    b.Property<string>("ResourceName")
                        .HasColumnType("longtext");

                    b.Property<string>("TrainingName")
                        .HasColumnType("longtext");

                    b.HasKey("ResourceId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("XR5_0TrainingRepo.Models.TrainingModule", b =>
                {
                    b.Property<string>("TrainingId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResourceList")
                        .HasColumnType("longtext");

                    b.Property<string>("TrainingName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UseCase")
                        .HasColumnType("longtext");

                    b.HasKey("TrainingId");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("XR5_0TrainingRepo.Models.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("UserEmail")
                        .HasColumnType("longtext");

                    b.Property<bool>("admin")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("UserName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("XR5_0TrainingRepo.Models.XR50App", b =>
                {
                    b.Property<string>("AppName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AdminName")
                        .HasColumnType("longtext");

                    b.Property<string>("AdminUserUserName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("OwncloudDirectory")
                        .HasColumnType("longtext");

                    b.Property<string>("OwncloudGroup")
                        .HasColumnType("longtext");

                    b.Property<string>("TrainingList")
                        .HasColumnType("longtext");

                    b.HasKey("AppName");

                    b.HasIndex("AdminUserUserName");

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("XR5_0TrainingRepo.Models.Asset", b =>
                {
                    b.HasOne("XR5_0TrainingRepo.Models.ResourceManagement", null)
                        .WithMany("AssetList")
                        .HasForeignKey("ResourceManagementResourceId");
                });

            modelBuilder.Entity("XR5_0TrainingRepo.Models.XR50App", b =>
                {
                    b.HasOne("XR5_0TrainingRepo.Models.User", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserUserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("XR5_0TrainingRepo.Models.ResourceManagement", b =>
                {
                    b.Navigation("AssetList");
                });
#pragma warning restore 612, 618
        }
    }
}
